[package]
name = "whisper-local-model"
version = "0.1.0"
edition = "2024"

[dependencies]
hypr-language = { workspace = true }
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }
