[package]
name = "llm-types"
version = "0.1.0"
edition = "2024"

[dependencies]
async-openai = { workspace = true }
nom = "8.0.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
rand = "0.9.0"
