[package]
name = "mp3"
version = "0.1.0"
edition = "2024"

[dependencies]
hound = { workspace = true }
hypr-audio-utils = { workspace = true }
mp3lame-encoder = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
